/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables.records;


import brs.schema.tables.LpBalances;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LpBalancesRecord extends UpdatableRecordImpl<LpBalancesRecord> implements Record6<Long, Long, Long, Long, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>DB.lp_balances.db_id</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>DB.lp_balances.db_id</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>DB.lp_balances.lp_id</code>.
     */
    public void setLpId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>DB.lp_balances.lp_id</code>.
     */
    public Long getLpId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>DB.lp_balances.token_id</code>.
     */
    public void setTokenId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>DB.lp_balances.token_id</code>.
     */
    public Long getTokenId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>DB.lp_balances.balance</code>.
     */
    public void setBalance(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>DB.lp_balances.balance</code>.
     */
    public Long getBalance() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>DB.lp_balances.height</code>.
     */
    public void setHeight(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DB.lp_balances.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DB.lp_balances.latest</code>.
     */
    public void setLatest(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>DB.lp_balances.latest</code>.
     */
    public Boolean getLatest() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Integer, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return LpBalances.LP_BALANCES.DB_ID;
    }

    @Override
    public Field<Long> field2() {
        return LpBalances.LP_BALANCES.LP_ID;
    }

    @Override
    public Field<Long> field3() {
        return LpBalances.LP_BALANCES.TOKEN_ID;
    }

    @Override
    public Field<Long> field4() {
        return LpBalances.LP_BALANCES.BALANCE;
    }

    @Override
    public Field<Integer> field5() {
        return LpBalances.LP_BALANCES.HEIGHT;
    }

    @Override
    public Field<Boolean> field6() {
        return LpBalances.LP_BALANCES.LATEST;
    }

    @Override
    public Long component1() {
        return getDbId();
    }

    @Override
    public Long component2() {
        return getLpId();
    }

    @Override
    public Long component3() {
        return getTokenId();
    }

    @Override
    public Long component4() {
        return getBalance();
    }

    @Override
    public Integer component5() {
        return getHeight();
    }

    @Override
    public Boolean component6() {
        return getLatest();
    }

    @Override
    public Long value1() {
        return getDbId();
    }

    @Override
    public Long value2() {
        return getLpId();
    }

    @Override
    public Long value3() {
        return getTokenId();
    }

    @Override
    public Long value4() {
        return getBalance();
    }

    @Override
    public Integer value5() {
        return getHeight();
    }

    @Override
    public Boolean value6() {
        return getLatest();
    }

    @Override
    public LpBalancesRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    @Override
    public LpBalancesRecord value2(Long value) {
        setLpId(value);
        return this;
    }

    @Override
    public LpBalancesRecord value3(Long value) {
        setTokenId(value);
        return this;
    }

    @Override
    public LpBalancesRecord value4(Long value) {
        setBalance(value);
        return this;
    }

    @Override
    public LpBalancesRecord value5(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public LpBalancesRecord value6(Boolean value) {
        setLatest(value);
        return this;
    }

    @Override
    public LpBalancesRecord values(Long value1, Long value2, Long value3, Long value4, Integer value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LpBalancesRecord
     */
    public LpBalancesRecord() {
        super(LpBalances.LP_BALANCES);
    }

    /**
     * Create a detached, initialised LpBalancesRecord
     */
    public LpBalancesRecord(Long dbId, Long lpId, Long tokenId, Long balance, Integer height, Boolean latest) {
        super(LpBalances.LP_BALANCES);

        setDbId(dbId);
        setLpId(lpId);
        setTokenId(tokenId);
        setBalance(balance);
        setHeight(height);
        setLatest(latest);
    }
}
