/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Keys;
import brs.schema.tables.records.LpRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lp extends TableImpl<LpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.lp</code>
     */
    public static final Lp LP = new Lp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LpRecord> getRecordType() {
        return LpRecord.class;
    }

    /**
     * The column <code>DB.lp.db_id</code>.
     */
    public final TableField<LpRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.lp.version</code>.
     */
    public final TableField<LpRecord, Byte> VERSION = createField(DSL.name("version"), SQLDataType.TINYINT.defaultValue(DSL.field("NULL", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>DB.lp.lp_id</code>.
     */
    public final TableField<LpRecord, Long> LP_ID = createField(DSL.name("lp_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp.name</code>.
     */
    public final TableField<LpRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>DB.lp.swap_fee</code>.
     */
    public final TableField<LpRecord, Integer> SWAP_FEE = createField(DSL.name("swap_fee"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp.platform_fee</code>.
     */
    public final TableField<LpRecord, Integer> PLATFORM_FEE = createField(DSL.name("platform_fee"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp.platform_account_id</code>.
     */
    public final TableField<LpRecord, Long> PLATFORM_ACCOUNT_ID = createField(DSL.name("platform_account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp.height</code>.
     */
    public final TableField<LpRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp.latest</code>.
     */
    public final TableField<LpRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private Lp(Name alias, Table<LpRecord> aliased) {
        this(alias, aliased, null);
    }

    private Lp(Name alias, Table<LpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.lp</code> table reference
     */
    public Lp(String alias) {
        this(DSL.name(alias), LP);
    }

    /**
     * Create an aliased <code>DB.lp</code> table reference
     */
    public Lp(Name alias) {
        this(alias, LP);
    }

    /**
     * Create a <code>DB.lp</code> table reference
     */
    public Lp() {
        this(DSL.name("lp"), null);
    }

    public <O extends Record> Lp(Table<O> child, ForeignKey<O, LpRecord> key) {
        super(child, key, LP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public Identity<LpRecord, Long> getIdentity() {
        return (Identity<LpRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LpRecord> getPrimaryKey() {
        return Keys.KEY_LP_PRIMARY;
    }

    @Override
    public Lp as(String alias) {
        return new Lp(DSL.name(alias), this);
    }

    @Override
    public Lp as(Name alias) {
        return new Lp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lp rename(String name) {
        return new Lp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lp rename(Name name) {
        return new Lp(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Byte, Long, String, Integer, Integer, Long, Integer, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
