/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Keys;
import brs.schema.tables.records.LpBalancesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LpBalances extends TableImpl<LpBalancesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.lp_balances</code>
     */
    public static final LpBalances LP_BALANCES = new LpBalances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LpBalancesRecord> getRecordType() {
        return LpBalancesRecord.class;
    }

    /**
     * The column <code>DB.lp_balances.db_id</code>.
     */
    public final TableField<LpBalancesRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.lp_balances.lp_id</code>.
     */
    public final TableField<LpBalancesRecord, Long> LP_ID = createField(DSL.name("lp_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp_balances.token_id</code>.
     */
    public final TableField<LpBalancesRecord, Long> TOKEN_ID = createField(DSL.name("token_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp_balances.balance</code>.
     */
    public final TableField<LpBalancesRecord, Long> BALANCE = createField(DSL.name("balance"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp_balances.height</code>.
     */
    public final TableField<LpBalancesRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp_balances.latest</code>.
     */
    public final TableField<LpBalancesRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private LpBalances(Name alias, Table<LpBalancesRecord> aliased) {
        this(alias, aliased, null);
    }

    private LpBalances(Name alias, Table<LpBalancesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.lp_balances</code> table reference
     */
    public LpBalances(String alias) {
        this(DSL.name(alias), LP_BALANCES);
    }

    /**
     * Create an aliased <code>DB.lp_balances</code> table reference
     */
    public LpBalances(Name alias) {
        this(alias, LP_BALANCES);
    }

    /**
     * Create a <code>DB.lp_balances</code> table reference
     */
    public LpBalances() {
        this(DSL.name("lp_balances"), null);
    }

    public <O extends Record> LpBalances(Table<O> child, ForeignKey<O, LpBalancesRecord> key) {
        super(child, key, LP_BALANCES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public Identity<LpBalancesRecord, Long> getIdentity() {
        return (Identity<LpBalancesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LpBalancesRecord> getPrimaryKey() {
        return Keys.KEY_LP_BALANCES_PRIMARY;
    }

    @Override
    public LpBalances as(String alias) {
        return new LpBalances(DSL.name(alias), this);
    }

    @Override
    public LpBalances as(Name alias) {
        return new LpBalances(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LpBalances rename(String name) {
        return new LpBalances(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LpBalances rename(Name name) {
        return new LpBalances(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
