/*
 * This file is generated by jOOQ.
 */
package brs.schema.tables;


import brs.schema.Db;
import brs.schema.Keys;
import brs.schema.tables.records.LpTokensRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LpTokens extends TableImpl<LpTokensRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB.lp_tokens</code>
     */
    public static final LpTokens LP_TOKENS = new LpTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LpTokensRecord> getRecordType() {
        return LpTokensRecord.class;
    }

    /**
     * The column <code>DB.lp_tokens.db_id</code>.
     */
    public final TableField<LpTokensRecord, Long> DB_ID = createField(DSL.name("db_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>DB.lp_tokens.lp_id</code>.
     */
    public final TableField<LpTokensRecord, Long> LP_ID = createField(DSL.name("lp_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp_tokens.token_id</code>.
     */
    public final TableField<LpTokensRecord, Long> TOKEN_ID = createField(DSL.name("token_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>DB.lp_tokens.factor</code>.
     */
    public final TableField<LpTokensRecord, Integer> FACTOR = createField(DSL.name("factor"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp_tokens.height</code>.
     */
    public final TableField<LpTokensRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>DB.lp_tokens.latest</code>.
     */
    public final TableField<LpTokensRecord, Boolean> LATEST = createField(DSL.name("latest"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("1", SQLDataType.BOOLEAN)), this, "");

    private LpTokens(Name alias, Table<LpTokensRecord> aliased) {
        this(alias, aliased, null);
    }

    private LpTokens(Name alias, Table<LpTokensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>DB.lp_tokens</code> table reference
     */
    public LpTokens(String alias) {
        this(DSL.name(alias), LP_TOKENS);
    }

    /**
     * Create an aliased <code>DB.lp_tokens</code> table reference
     */
    public LpTokens(Name alias) {
        this(alias, LP_TOKENS);
    }

    /**
     * Create a <code>DB.lp_tokens</code> table reference
     */
    public LpTokens() {
        this(DSL.name("lp_tokens"), null);
    }

    public <O extends Record> LpTokens(Table<O> child, ForeignKey<O, LpTokensRecord> key) {
        super(child, key, LP_TOKENS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Db.DB;
    }

    @Override
    public Identity<LpTokensRecord, Long> getIdentity() {
        return (Identity<LpTokensRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LpTokensRecord> getPrimaryKey() {
        return Keys.KEY_LP_TOKENS_PRIMARY;
    }

    @Override
    public LpTokens as(String alias) {
        return new LpTokens(DSL.name(alias), this);
    }

    @Override
    public LpTokens as(Name alias) {
        return new LpTokens(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LpTokens rename(String name) {
        return new LpTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LpTokens rename(Name name) {
        return new LpTokens(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
